apiVersion: v1
kind: ServiceAccount
metadata:
  name: neurokube-brain-sa
  namespace: neurokube
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: neurokube-brain-role
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "patch", "update"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: neurokube-brain-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: neurokube-brain-role
subjects:
  - kind: ServiceAccount
    name: neurokube-brain-sa
    namespace: neurokube
